nelmio_api_doc:
  documentation:
    info:
      title: My App
      description: Crud Operations with a relationnal mapping with a database using FOSRESTBundle, FOSUserBundle and SONATAAdminBundle
      version: 1.0.0
    securityDefinitions:
      Bearer:
        type: apiKey
        description: 'Value: Bearer {jwt}'
        name: Authorization
        in: header
    security:
      - Bearer: []
  models: { use_jms: false }
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
